postsubmits:
  - name: post-banka-4-frontend-build
    always_run: true
    decorate: true
    max_concurrency: 1
    labels:
      preset-harbor-robot-push: "true"
      preset-k8s-banka-4: "true"
    spec:
      containers:
        - image: harbor.k8s.elab.rs/base-images/base:java-21-node-18-docker
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail

              # PROMENITI PRI KOPIRANJU
              # Naziv vašeg tima, može biti "banka-1", "banka-2", "banka-3", ili "banka-4"
              TEAM_NAME="banka-4"

              # Pokreće Docker unutar kontejnera u kome se izvršava ova skripta.
              # Docker vam omogućava da buildujete images.
              start-docker.sh

              # Logovanje na našu Harbor instancu na koju ćemo da pushujemo image.
              docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD harbor.k8s.elab.rs

              # Hash commit-a za koji se ovaj job pokrenuo. Ovaj hash koristimo da pushujemo
              # image koji ima ovaj hash kao svoj tag.
              commit_hash=$(git rev-parse HEAD)

              # Builduje Docker image sa "latest" tagom i nazivom takvim da možemo da pushujemo
              # image na našu Harbor instancu.
              docker build --build-arg APP_ENV=build-prod -t harbor.k8s.elab.rs/${TEAM_NAME}/frontend:latest .

              # Pravi kopiju prethodno buildovanog image sa tagom zasnovanim na commit hash-u.
              docker tag harbor.k8s.elab.rs/${TEAM_NAME}/frontend:latest harbor.k8s.elab.rs/${TEAM_NAME}/frontend:${commit_hash}

              # Pushuje oba image na našu Harbor instancu.
              docker push harbor.k8s.elab.rs/${TEAM_NAME}/frontend:latest
              docker push harbor.k8s.elab.rs/${TEAM_NAME}/frontend:${commit_hash}

              docker build --build-arg APP_ENV=build-dev -t harbor.k8s.elab.rs/${TEAM_NAME}/frontend-dev:latest .

              # Pravi kopiju prethodno buildovanog image sa tagom zasnovanim na commit hash-u.
              docker tag harbor.k8s.elab.rs/${TEAM_NAME}/frontend-dev:latest harbor.k8s.elab.rs/${TEAM_NAME}/frontend-dev:${commit_hash}

              # Pushuje oba image na našu Harbor instancu.
              docker push harbor.k8s.elab.rs/${TEAM_NAME}/frontend-dev:latest
              docker push harbor.k8s.elab.rs/${TEAM_NAME}/frontend-dev:${commit_hash}

              helm upgrade --namespace="$TEAM_NAME-dev" --create-namespace --timeout=20m --atomic --install --set imageTag="${commit_hash}" "$TEAM_NAME-frontend" "oci://harbor.k8s.elab.rs/$TEAM_NAME/$TEAM_NAME-frontend/$TEAM_NAME-frontend"
              if [ "$PULL_BASE_REF" == "main" ]; then
                helm upgrade --namespace="$TEAM_NAME-prod" --create-namespace --timeout=20m --atomic --install --set imageName="frontend",imageTag="${commit_hash}",host="$TEAM_NAME.si.raf.edu.rs" "$TEAM_NAME-frontend" "oci://harbor.k8s.elab.rs/$TEAM_NAME/$TEAM_NAME-frontend/$TEAM_NAME-frontend"
              fi
          securityContext:
            privileged: true
          imagePullPolicy: Always
