version: '3.8'
services:
    db:
        image: postgres:14
        container_name: db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
            - POSTGRES_DB=moja_banka_db
        restart: unless-stopped
        volumes:
            - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        networks:
            - backend-network
    
    redis:
        image: 'redis:latest'
        container_name: rdb
        ports:
            - "6379:6379"
        restart: unless-stopped
        networks:
            - backend-network
    
    user-service:
        image: commandlinefox/user-service:latest
        environment:
            - SPRING.DATASOURCE.URL=jdbc:postgresql://db:5432/moja_banka_db
        ports:
            - "8080:8080"
        container_name: user-service 
        restart: unless-stopped
        networks:
            - backend-network

    banka-service:
        image: commandlinefox/banka-service:latest
        environment:
            - SPRING.DATASOURCE.URL=jdbc:postgresql://db:5432/moja_banka_db
        ports:
            - "8082:8082"
        container_name: banka-service 
        restart: unless-stopped
        networks:
            - backend-network
    
    berza-service:
        image: commandlinefox/berza-service:latest
        environment:
            - SPRING.DATASOURCE.URL=jdbc:postgresql://db:5432/moja_banka_db
        ports:
            - "8081:8081"
        container_name: berza-service
        restart: unless-stopped
        networks:
            - backend-network    

networks:
    backend-network:
        driver: bridge